### Create a category
POST http://localhost:5000/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "Computer Science"
}

### Get all category
GET http://localhost:5000/api/categories
Accept: application/json

### Get category by id
GET http://localhost:5000/api/categories/ff00fe2b-56fc-4465-a946-b388732da97a
Accept: application/json

### Update category
PUT http://localhost:5000/api/categories/ff00fe2b-56fc-4465-a946-b388732da97a
Accept: application/json
Content-Type: application/json

{
  "name": "Algorithm"
}

### Delete category
DELETE http://localhost:5000/api/categories/ff00fe2b-56fc-4465-a946-b388732da97a
Accept: application/json
