### Create a category
POST http://localhost:5000/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "Computer Science"
}

### Get all category
GET http://localhost:5000/api/categories
Accept: application/json

### Get category by id
GET http://localhost:5000/api/categories/0449a91a-3a53-4e1c-aac7-b57b9513434b
Accept: application/json

### Update category
PUT http://localhost:5000/api/categories/0449a91a-3a53-4e1c-aac7-b57b9513434b
Accept: application/json
Content-Type: application/json

{
  "name": "Algorithm"
}

### Delete category
DELETE http://localhost:5000/api/categories/0449a91a-3a53-4e1c-aac7-b57b9513434b
Accept: application/json

### Create a question
POST http://localhost:5000/api/categories/2ea8d036-e049-47b5-b057-0b9d47ddb6ea/questions
Accept: application/json
Content-Type: application/json

{
  "question": "The founder of Linux is?",
  "answers": [
    {
      "answer": "Bill Gates",
      "isCorrect": false
    },
    {
      "answer": "Mark Zuckerberg",
      "isCorrect": false
    },
    {
      "answer": "Linus Torvalds",
      "isCorrect": true
    },
    {
      "answer": "Jack Ma",
      "isCorrect": false
    }
  ]
}